import type { RuleMetadata } from "./types.js";

export const KEYBOARD_RULES: RuleMetadata[] = [
  {
    id: "keyboard-focus-lost",
    title: "Keyboard focus was lost during Tab navigation",
    description: "Tab navigation did not land on a usable focused element.",
    profile: "keyboard",
    defaultSeverity: "high",
    confidence: "high",
    automation: "automated",
    standards: ["WCAG 2.2 2.1.1 related"],
    limitations: ["Does not verify that every control can be operated."],
  },
  {
    id: "keyboard-focus-cycle",
    title: "Unexpected keyboard focus cycle detected",
    description: "Focus repeated among elements before the tab limit without reaching new content.",
    profile: "keyboard",
    defaultSeverity: "medium",
    confidence: "medium",
    automation: "heuristic",
    standards: ["WCAG 2.2 2.1.2 related"],
    limitations: ["Modals and widgets may legitimately trap focus while open."],
  },
  {
    id: "keyboard-focus-offscreen",
    title: "Focused element is outside the viewport",
    description: "Keyboard focus moved to an element that is not visible in the viewport and was not scrolled into view.",
    profile: "keyboard",
    defaultSeverity: "medium",
    confidence: "high",
    automation: "automated",
    standards: ["WCAG 2.2 2.4.3 related"],
    limitations: ["Does not judge whether offscreen focus is intentional."],
  },
  {
    id: "keyboard-focus-hidden",
    title: "Focused element appears hidden",
    description: "The active element has no visible bounding box or is hidden while still receiving focus.",
    profile: "keyboard",
    defaultSeverity: "high",
    confidence: "high",
    automation: "automated",
    standards: ["WCAG 2.2 2.1.1 related"],
    limitations: ["Custom focus styling is not fully evaluated."],
  },
  {
    id: "keyboard-excessive-tab-stops",
    title: "Tab stop count exceeded configured limit",
    description: "The keyboard traversal exceeded the configured tab stop limit before completing.",
    profile: "keyboard",
    defaultSeverity: "minor",
    confidence: "medium",
    automation: "heuristic",
    standards: ["WCAG 2.2 2.4.3 related"],
    limitations: ["Large pages may require more stops than the configured limit."],
  },
  {
    id: "keyboard-positive-tabindex",
    title: "Positive tabindex detected",
    description: "An element uses tabindex greater than zero, which can disrupt expected focus order.",
    profile: "keyboard",
    defaultSeverity: "medium",
    confidence: "high",
    automation: "heuristic",
    standards: ["WCAG 2.2 2.4.3 related"],
    limitations: ["Positive tabindex may be intentional in legacy interfaces."],
  },
  {
    id: "keyboard-unreachable-native-control",
    title: "Visible native control may be unreachable by keyboard",
    description: "A visible enabled native control was not reached during the keyboard traversal.",
    profile: "keyboard",
    defaultSeverity: "medium",
    confidence: "medium",
    automation: "heuristic",
    standards: ["WCAG 2.2 2.1.1 related"],
    limitations: ["Custom components and disabled-looking controls may be misclassified."],
  },
  {
    id: "focus-indicator-review",
    title: "Focus indicator requires manual review",
    description: "No obvious focus indicator change was detected for a focused element.",
    profile: "keyboard",
    defaultSeverity: "medium",
    confidence: "low",
    automation: "manual-review",
    standards: ["WCAG 2.2 1.4.11 related"],
    limitations: ["Applications may use non-outline focus indicators this heuristic cannot detect."],
  },
];

export const LARGE_TEXT_RULES: RuleMetadata[] = [
  {
    id: "large-text-horizontal-overflow",
    title: "Horizontal overflow after text scaling",
    description: "Text scaling introduced significant horizontal overflow that was not present at the default size.",
    profile: "large-text",
    defaultSeverity: "medium",
    confidence: "high",
    automation: "heuristic",
    standards: ["WCAG 2.2 1.4.10 related"],
    limitations: ["Does not verify full 400% reflow."],
  },
  {
    id: "large-text-clipped-content",
    title: "Text content appears clipped after scaling",
    description: "Visible text may be clipped by a container with insufficient space.",
    profile: "large-text",
    defaultSeverity: "medium",
    confidence: "medium",
    automation: "heuristic",
    standards: ["WCAG 2.2 1.4.4 related"],
    limitations: ["Clipping heuristics may miss subtle truncation."],
  },
  {
    id: "large-text-overlap",
    title: "Overlapping content after text scaling",
    description: "Text or controls overlap significantly after scaling and did not overlap at the default size.",
    profile: "large-text",
    defaultSeverity: "medium",
    confidence: "medium",
    automation: "heuristic",
    standards: ["WCAG 2.2 1.4.4 related"],
    limitations: ["Small overlaps within tolerance are ignored."],
  },
  {
    id: "large-text-content-hidden",
    title: "Content hidden after text scaling",
    description: "Content visible at the default size is no longer visible after text scaling.",
    profile: "large-text",
    defaultSeverity: "high",
    confidence: "medium",
    automation: "heuristic",
    standards: ["WCAG 2.2 1.4.4 related"],
    limitations: ["Responsive reflow may intentionally hide secondary content."],
  },
  {
    id: "large-text-control-truncation",
    title: "Control text appears truncated",
    description: "Button, input, or control text appears clipped after scaling.",
    profile: "large-text",
    defaultSeverity: "medium",
    confidence: "medium",
    automation: "heuristic",
    standards: ["WCAG 2.2 1.4.4 related"],
    limitations: ["Icon-only controls may not expose visible text."],
  },
  {
    id: "large-text-fixed-dimension-risk",
    title: "Fixed-size text container risk",
    description: "A text container uses fixed dimensions with clipping that may hide scaled content.",
    profile: "large-text",
    defaultSeverity: "minor",
    confidence: "low",
    automation: "heuristic",
    standards: ["WCAG 2.2 1.4.4 related"],
    limitations: ["Fixed dimensions may be acceptable when content still fits."],
  },
];

export const REDUCED_MOTION_RULES: RuleMetadata[] = [
  {
    id: "reduced-motion-preference-not-applied",
    title: "Reduced motion preference not applied",
    description: "The page does not report prefers-reduced-motion: reduce in this profile context.",
    profile: "reduced-motion",
    defaultSeverity: "high",
    confidence: "high",
    automation: "automated",
    standards: ["WCAG 2.2 2.3.3 related"],
    limitations: ["Environment emulation failures may cause false positives."],
  },
  {
    id: "reduced-motion-infinite-animation",
    title: "Infinite animation remains active under reduced motion",
    description: "A significant infinite animation is still active when reduced motion is requested.",
    profile: "reduced-motion",
    defaultSeverity: "medium",
    confidence: "high",
    automation: "heuristic",
    standards: ["WCAG 2.2 2.3.3 related"],
    limitations: ["Essential animations may remain by design."],
  },
  {
    id: "reduced-motion-motion-unchanged",
    title: "Animation unchanged under reduced motion",
    description: "A significant animation appears unchanged compared with the default profile.",
    profile: "reduced-motion",
    defaultSeverity: "medium",
    confidence: "medium",
    automation: "heuristic",
    standards: ["WCAG 2.2 2.3.3 related"],
    limitations: ["Short decorative transitions may be acceptable."],
  },
  {
    id: "reduced-motion-long-animation",
    title: "Long animation remains active under reduced motion",
    description: "Movement continues longer than the configured threshold under reduced motion.",
    profile: "reduced-motion",
    defaultSeverity: "medium",
    confidence: "medium",
    automation: "heuristic",
    standards: ["WCAG 2.2 2.3.3 related"],
    limitations: ["Progress indicators may require motion."],
  },
  {
    id: "reduced-motion-scroll-behavior",
    title: "Smooth scrolling remains active under reduced motion",
    description: "Smooth scroll behavior appears active when reduced motion is requested.",
    profile: "reduced-motion",
    defaultSeverity: "minor",
    confidence: "medium",
    automation: "heuristic",
    standards: ["WCAG 2.2 2.3.3 related"],
    limitations: ["Scroll behavior detection is approximate."],
  },
  {
    id: "reduced-motion-review",
    title: "Remaining motion requires manual review",
    description: "Motion was detected whose accessibility impact cannot be determined automatically.",
    profile: "reduced-motion",
    defaultSeverity: "minor",
    confidence: "low",
    automation: "manual-review",
    standards: ["WCAG 2.2 2.3.3 related"],
    limitations: ["Manual review is required to judge essential motion."],
  },
];

export const FLOW_RULES: RuleMetadata[] = [
  {
    id: "dialog-focus-entry",
    title: "Focus did not move into the opened dialog",
    description: "A dialog became visible but keyboard focus remained outside the dialog.",
    context: "flow",
    defaultSeverity: "high",
    confidence: "medium",
    automation: "heuristic",
    standards: ["WCAG 2.2 2.4.3 related"],
    limitations: ["Cannot determine whether focus moved via non-standard styling."],
  },
  {
    id: "dialog-focus-return-review",
    title: "Dialog closed without clear focus return",
    description: "Focus may not have returned to the dialog trigger after closing.",
    context: "flow",
    defaultSeverity: "medium",
    confidence: "low",
    automation: "manual-review",
    standards: ["WCAG 2.2 2.4.3 related"],
    limitations: ["Manual review is required when focus moves to a logical alternative."],
  },
  {
    id: "route-change-focus-review",
    title: "Route changed without observable focus management",
    description: "SPA navigation occurred without detectable focus management.",
    context: "flow",
    defaultSeverity: "medium",
    confidence: "low",
    automation: "manual-review",
    standards: ["WCAG 2.2 2.4.3 related"],
    limitations: ["Does not judge whether focus moved to expected page content."],
  },
  {
    id: "form-error-focus-review",
    title: "Form errors appeared without focus on an error target",
    description: "Validation errors became visible without focus on summary or invalid control.",
    context: "flow",
    defaultSeverity: "medium",
    confidence: "low",
    automation: "heuristic",
    standards: ["WCAG 2.2 3.3.1 related"],
    limitations: ["Custom error presentation may not be detected."],
  },
  {
    id: "interactive-state-keyboard-trap",
    title: "Possible keyboard trap in interactive state",
    description: "Focus may be trapped unexpectedly within an opened interactive state.",
    context: "flow",
    defaultSeverity: "medium",
    confidence: "medium",
    automation: "heuristic",
    standards: ["WCAG 2.2 2.1.2 related"],
    limitations: ["Modal focus containment may be correct while open."],
  },
  {
    id: "status-message-review",
    title: "Status change may lack a live region",
    description: "Important status changes may not be exposed to assistive technologies.",
    context: "flow",
    defaultSeverity: "minor",
    confidence: "low",
    automation: "manual-review",
    standards: ["WCAG 2.2 4.1.3 related"],
    limitations: ["Does not verify screen reader announcements."],
  },
];

const ALL_RULES = [...KEYBOARD_RULES, ...LARGE_TEXT_RULES, ...REDUCED_MOTION_RULES, ...FLOW_RULES];

export function listRuleMetadata(): RuleMetadata[] {
  return [...ALL_RULES].sort((a, b) => a.id.localeCompare(b.id));
}

export function getRuleMetadata(ruleId: string): RuleMetadata | undefined {
  return ALL_RULES.find((rule) => rule.id === ruleId);
}
